### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ecrofeg** [ecrofeg/bochkogram#1]
- [ ] Pinned message
- [ ] Markdown support
- [ ] Add "Reply message" function
- [ ] Load images by URL
- [ ] Load images by pasting them with `CTRL+V`
- [ ] Emojis tab
- [ ] Message editing
- [ ] Chats and groups
- [ ] Private chats
- [ ] Notifications & Mentioning
- [ ] Unread messages
- [ ] Online users
- [x] Logout
- [x] Replace links with real `<a ...></a>` tag
- [x] Split old messages

**Comment by kfimchenko** [comment]
Amount of unread messages in title

**Comment by kfimchenko** [comment]
Online users list
